### ISSUE TITLE
Implementing ILogger

### ISSUE THREAD

**Issue by almightydegu** [introtocomputerscience/azure-function-autofac-dependency-injection#18]
Using this framework what is the recommended way of implementing ILogger so that it can be used in all services?

**Comment by rawrspace** [comment]
That is more of a question about using Autofac rather than this particular package it seems.

Currently Azure Functions natively supports injection either a TraceWriter or an ILogger simply by adding a parameter of that type to the function method signature. 

This package is used for injecting other services into the function methods. However the classes you inject can also have classes injected to them and that seems like the place I think you are asking this question about. If that is true then I would recommend using the [LoggerFactory](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerfactory?view=aspnetcore-2.1) to create an instance of the logger you want and then simply register it with autofac as a single instance ILogger. Then in any of your services you can add the ILogger parameter and it will be injected.
