### ISSUE TITLE
package installation error.

### ISSUE THREAD

**Issue by michaelsync** [introtocomputerscience/azure-function-autofac-dependency-injection#2]
I am getting this error when I install your nuget package. 

1. 

Install-Package : Version conflict detected for Microsoft.Azure.WebJobs. Reference the package directly from the project to resolve this issue. 
 Medirecords.Functions -> AzureFunctions.Autofac 2.0.0 -> Microsoft.Azure.WebJobs (>= 2.1.0-beta4) 
 Medirecords.Functions -> Microsoft.NET.Sdk.Functions 1.0.2 -> Microsoft.Azure.WebJobs (= 2.1.0-beta1).

2. If I have a JSON.net installed, I got this error. 

Restoring packages for C:\TelstraHealth\healthbiz\Medirecords\Medirecords.Functions\Medirecords.Functions.csproj...
Detected package version outside of dependency constraint: Microsoft.NET.Sdk.Functions 1.0.2 requires Newtonsoft.Json (= 9.0.1) but version Newtonsoft.Json 10.0.3 was resolved.
Install-Package : Version conflict detected for Microsoft.Azure.WebJobs. Reference the package directly from the project to resolve this issue.

**Comment by rawrspace** [comment]
For the first error you need to upgrade from Microsoft.NET.Sdk.Functions 1.0.2 to at least Microsoft.NET.Sdk.Functions 1.0.4 or greater. This is due to the dependency on Microsoft.Azure.WebJobs version 2.1.0-beta4 by this package.

The second error is not actually related to my package but is due to the hard dependency of Microsoft.NET.Sdk.Functions on Newtonsoft.Json 9.0.1. You will need to install that version of Newtonsoft.Json to use Microsoft.NET.Sdk.Functions. You can read more about the dependencies here: [Microsoft.NET.Sdk.Functions](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/)
