### ISSUE TITLE
Nuget package with netstandard2.0

### ISSUE THREAD

**Issue by Andras-Csanyi** [introtocomputerscience/azure-function-autofac-dependency-injection#3]
Hi,

Could you publish a nuget package with netstandard2.0? This way I could use this package together with durable functions.

Thanks

**Comment by rawrspace** [comment]
I am currently using this with durable function. Are you running a functions v2 project that targets .net core instead of a functions v1 project? I will look into creating a netstandard version.

**Comment by rawrspace** [comment]
Currently Microsoft.Azure.WebJobs does not have support for netstandard2.0 so I am unable to upgrade the main package to support it. The beta of Microsoft.Azure.WebJobs starting at v3 starts to support netstandard2.0 so once Microsoft.NET.Sdk.Functions allows that version of Microsoft.Azure.WebJobs then I could make it work. 

It may also be possible to create a seperate project that specifically target netstandard so that the .NET framework version can target v2 of webjobs and netstandard can target v3. I will look into this.

**Comment by LeastOne** [comment]
@vandersmissenc, my recommendation would be to create your own v3-beta branch and corresponding pre-release to nuget. This would allow you to have the best of both worlds. Those willing to depend on the v2 of Azure Functions and v3 of WebJobs could make the choice to also rely on your v3-beta. Others wanting the stability of v1 Azure Functions could continue to rely on your v2 master branch to which you could still patch and update as necessary.

As an FYI, I cloned the project and converted it to netstandard using v3 WebJobs. Strangely I initially encountered an odd `ReflectionTypeLoadException` which I narrowed down to an issue with Autofac v4.8.1. I worked around it by downgrading to Autofac v4.6.1 (I chose v4.6.1 because I'm successfully using it in other projects). I stopped my research there but there appears to potentially be some sort of breaking change between v4.6.1 and v4.8.1 of Autofac.

**Comment by rawrspace** [comment]
I converted the package over to .NET Standard and created sample projects for .NET Framework and .NET Core. Please let me know if you see issues in the new version. https://www.nuget.org/packages/AzureFunctions.Autofac/
