### ISSUE TITLE
README.md has wrong information for Named instances registering in ContainerBuilder

### ISSUE THREAD

**Issue by nadzzz** [introtocomputerscience/azure-function-autofac-dependency-injection#30]
**Describe the bug**
In the readme file, the section where it shows an example where we can register named instance contains error. We need to specify As<Interface>() before the named instance for proper named registration

**To Reproduce**
1. Create a azure funcitons project
2. Create a DIConfig class and paste the code in examples
3. Create the related classes and interfaces skeletons that are used in the sample

4. Use [Inject("<name>")] parameter in your sample funciton
5. Debug and break in the function body.

**Expected behavior**
The object is injected

**Observed behavior**
The object is null

**Comment by rawrspace** [comment]
I will try to verify this behavior this evening. I have used only Named without issues. You can see run the examples within the code to verify this: https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/blob/master/NetFrameworkExample/Modules/TestModule.cs

I believe the issue is that you provided an empty string to the Inject attribute. You should be providing the name of instance you wish to resolve. If it fails to locate the instance with a matching name I believe it is returning null which is what you are seeing.

**Comment by rawrspace** [comment]
I reviewed the example projects in the repo and they work fine with simply using .Named . I suspect your issue is that you are passing an empty string to the Inject attribute. If you are using a named instance you need to pass the name in order for it to resolve. If you still believe your issue exists then please provide a reproduction project I can examine.

**Comment by nadzzz** [comment]
From what I remembered, it was not the case. my [Inject("")] had a name. It is true that my repro steps was not clear. 

I tested with named Inject attribute. Since you tell that this is the expected behavior to not have As<> in front of Named<>, I will try again tomorrow. 

Best regards
