### ISSUE TITLE
Access request in DIConfig

### ISSUE THREAD

**Issue by subhendu-de** [introtocomputerscience/azure-function-autofac-dependency-injection#36]
I have a requirement to read the metadata from "HttpRequestMessage request" and pass it to parameter in a constructor using .WithParameters. Is it possible to access request parameter in DIConfig class?

**Comment by rawrspace** [comment]
If you could provide an example I could answer more definitively. I believe that since dependencies are resolved before the HttpRequestMessage is set you would not be able to pass that in. a possible solution would be to allow the DI container to be injected or accessed and you could manually resolve your dependencies. Again, I would need to understand your example further.

**Comment by subhendu-de** [comment]
I will come back to you later. We found a workaround for now.
