### ISSUE TITLE
Constructor Injection

### ISSUE THREAD

**Issue by javaadpatel** [introtocomputerscience/azure-function-autofac-dependency-injection#55]
Is it possible to add support for constructor injection? I'm unsure of the technicals of how this is built, so apologies if this is a dumb question.

**Comment by rawrspace** [comment]
Can you clarify your question and potentially provide an example? Since this is just Autofac when you register all the dependencies with the container they can be injected into the constructors without a problem.

If you are asking if it is possible to create a construction on the function itself and inject there then the answer is no. That is an unusual use case however so I don't think that is what you are probably trying to do.

**Comment by javaadpatel** [comment]
Sure, this is an example of what I'm trying to do:
```
    [DependencyInjectionConfig(typeof(DIConfig))]
    public class Function1
    {
        private readonly ISampleService _sampleService;

        public Function1([Inject] ISampleService sampleService)
        {
            _sampleService = sampleService;
        }

        [FunctionName("Function1")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            _sampleService.Add();
           ....
       }
```

I have quite a few dependencies (this ofcourse is simplified) but I would like to inject them in the class constructor so that I don't have to have all of them as function parameters.

**Comment by rawrspace** [comment]
Okay from that example that is not possible due to the way that we have to hook into the functions.

One possible solution, albeit less than ideal I know, is to create an object that accepts all the dependencies and then inject that single object into each function.

Let me know if you have any further questions about this.
