### ISSUE TITLE
Constructor not found for DI class with ctor signature DIConfig(string functionName, string baseDirectory, ILoggerFactory factory)

### ISSUE THREAD

**Issue by malaker** [introtocomputerscience/azure-function-autofac-dependency-injection#67]
**Describe the bug**

**To Reproduce**
1) Implement function v3 according to documentation in the project
2) Implement test according to documentation

**Expected behavior**
Test passes

Current behaviour:

 Message: 
    Test method TestProject1.UnitTest1.TestMethod1 threw exception: 
    System.MissingMethodException: Constructor on type 'FunctionApp1.DIConfig' not found.
  Stack Trace: 
    RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
    Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
    DependencyInjection.VerifyConfiguration(Type type, Boolean verifyUnnecessaryConfig)
    UnitTest1.TestMethod1() line 13

**Additional context**

**Comment by rawrspace** [comment]
Please share a reproduction project

**Comment by malaker** [comment]
Can I get permissions to contribute so that I can create branch that shows the issue?

**Comment by malaker** [comment]
https://github.com/introtocomputerscience/azure-function-autofac-dependency-injection/compare/master...malaker:issue/67-DI-verification-not-working-for-fv2-fv3?expand=1

**Comment by rawrspace** [comment]
I corrected the issue and pushed a new version to NuGet. It will be available shortly here: https://www.nuget.org/packages/AzureFunctions.Autofac/4.0.3

The issue was that when that code was originally contributed you could only create a Dependency Injection Config with the function name. As I added support for app directory and Logger the code was not updated for verification and the way the tests were written it still passed.

I resolved the issue by adding the same logic that is used in the primary code for determining which constructor to use for instantiating the instance.
