### ISSUE TITLE
Support for HttpRequestMessage parameter in DI class

### ISSUE THREAD

**Issue by malaker** [introtocomputerscience/azure-function-autofac-dependency-injection#68]
**Describe the solution you'd like**

 public class DIConfig
    {
        public DIConfig(string functionName, string baseDirectory, ILoggerFactory factory, HttpRequestMessage request)
        {
            DependencyInjection.Initialize(builder =>
            {
                builder.RegisterModule(new TestModule());
                builder.Register<DirectoryAnnouncer>(c => new DirectoryAnnouncer(baseDirectory)).As<IAnnouncer>();
                builder.RegisterLoggerFactory(factory);
            }, functionName);
        }
    }

Adding support for HttpRequestMessage will enable different scenarios of DI container configuration.

Example

based on query parameters it would be possible in dynamic way configure and use different logic implementations

**Comment by rawrspace** [comment]
I have a few concerns about being able to do this. 

1. Functions V3 switched to HttpRequest instead of HttpRequestMessage so hardcoding this to HttpRequestMessage either implies the user is on V2 functions or requires them to use HttpRequestMessage in V3 instead of HttpRequest.
2. The instantiation of the DIConfig happens before you have the HttpRequestMessage so it wouldn't be possible to pass it in as a parameter in the InjectBindingProvider class.

Do you have an example or explanation of what exactly you are trying to accomplish?

**Comment by malaker** [comment]
Ok, understood. Having incoming request would enable some quite advanced scenario :) based on query parameters from request DI container could have different configuration :)
